"""
Comprehensive test script for the swim program director workflow.
Tests the complete pipeline: macro_agent -> meso_agent -> micro_agent
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
import json
from datetime import datetime
from lib.state import (
    AgentState, AthleteProfile, Vitals, SkillLevel, StrengthKPIs,
    SwimData, Meet, MacroCycle, MesoCycleStub, PhaseType, FocusType, StrokeFocus
)
from lib.graph import app

load_dotenv()

# ══════════════════════════════════════════════════════════════════════════════
# TEST DATA: Create a sample athlete profile
# ══════════════════════════════════════════════════════════════════════════════

def create_test_athlete() -> AthleteProfile:
    """Create a sample elite-level swimmer for testing."""
    return AthleteProfile(
        vitals=Vitals(age="17", height="6'1\""),
        skillLevel=SkillLevel.ELITE,
        stroke_focus=StrokeFocus.FREESTYLE,  # Add if missing
        kpis=StrengthKPIs(
            backsquat="225",
            deadlift="275",
            benchpress="185",
            powerclean="155",
            snatch="115",
            verticalleap="28"
        ),
        swimData=SwimData(
            events=["50 Freestyle", "100 Butterfly"],
            times={"50 Freestyle": "23.04", "100 Butterfly": "55.07"}
        ),
        meets=[Meet(name="State Championships", date="2026-02-15")],
        agentNotes="Focus on aerobic base and technique. Building towards peak season in February."
    )


# ══════════════════════════════════════════════════════════════════════════════
# TEST: Full Workflow Pipeline
# ══════════════════════════════════════════════════════════════════════════════

def test_full_workflow():
    """Test the complete workflow from macro planning to micro planning."""
    
    print("\n" + "="*80)
    print("TESTING FULL WORKFLOW: macro_agent -> meso_agent -> micro_agent")
    print("="*80)
    
    # Create initial state
    athlete = create_test_athlete()
    
    initial_state = AgentState(
        athlete_profile=athlete,
        macro_plan=None,  # Will be generated by macro_agent
        meso_plan=[],
        micro_plan=[],
        daily_workouts=[],
        messages=[],
        next_agent="macro",
        current_phase="macro"
    )
    
    print(f"\nStarting workflow with athlete:")
    print(f"   - Skill Level: {athlete.skillLevel.value}")
    print(f"   - Age: {athlete.vitals.age}")
    print(f"   - Target Meet: {athlete.meets[0].name} ({athlete.meets[0].date})")
    
    try:
        # Run the compiled graph
        print("\nExecuting workflow graph...")
        result = app.invoke(initial_state)
        
        print("\nWorkflow completed successfully!")
        
        # ────────────────────────────────────────────────────────────────────────
        # Verify macro_plan output
        # ────────────────────────────────────────────────────────────────────────
        if result.get("macro_plan"):
            macro = result["macro_plan"]
            print(f"\nMACRO PLAN:")
            print(f"   - Cycle Start: {macro.cycle_start_date}")
            print(f"   - Target Meet: {macro.target_meet.name}")
            print(f"   - Mesocycles: {len(macro.mesocycle_stubs)}")
            for i, meso_stub in enumerate(macro.mesocycle_stubs, 1):
                print(f"      {i}. {meso_stub.phase.value} - {meso_stub.num_weeks} weeks ({meso_stub.focus.value})")
        else:
            print(f"ERROR: No macro_plan generated. Error: {result.get('error')}")
            return False
        
        # ────────────────────────────────────────────────────────────────────────
        # Verify meso_plan output
        # ────────────────────────────────────────────────────────────────────────
        if result.get("meso_plan"):
            meso_plans = result["meso_plan"]
            print(f"\nMESO PLANS: {len(meso_plans)} mesocycles generated")
            for i, meso in enumerate(meso_plans, 1):
                print(f"   Mesocycle {i}:")
                print(f"      - Microcycles: {len(meso.micro_cycle_stubs)}")
                for j, micro_stub in enumerate(meso.micro_cycle_stubs, 1):
                    print(f"         Week {j}: {micro_stub.focus.value} ({micro_stub.target_yardage} yards)")
        else:
            print(f"ERROR: No meso_plan generated. Error: {result.get('error')}")
            return False
        
        # ────────────────────────────────────────────────────────────────────────
        # Verify micro_plan output
        # ────────────────────────────────────────────────────────────────────────
        if result.get("micro_plan"):
            micro_plans = result["micro_plan"]
            print(f"\nMICRO PLANS: {len(micro_plans)} workouts generated")
            for i, micro in enumerate(micro_plans[:5], 1):  # Show first 5
                print(f"   Workout {i}: {micro.focus.value} ({micro.target_yardage} yards) - {micro.stroke_focus.value}")
            if len(micro_plans) > 5:
                print(f"   ... and {len(micro_plans) - 5} more workouts")
        else:
            print(f"WARNING: No micro_plan generated. Error: {result.get('error')}")
        
        return True
        
    except Exception as e:
        print(f"\nWORKFLOW FAILED: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return False


# ══════════════════════════════════════════════════════════════════════════════
# TEST: Individual Agent Testing
# ══════════════════════════════════════════════════════════════════════════════

def test_macro_agent_only():
    """Test only the macro agent."""
    from lib.agents import macro_agent
    
    print("\n" + "="*80)
    print("TESTING MACRO AGENT ONLY")
    print("="*80)
    
    athlete = create_test_athlete()
    state = AgentState(
        athlete_profile=athlete,
        macro_plan=None,
        meso_plan=[],
        micro_plan=[],
        daily_workouts=[],
        messages=[],
        next_agent="macro",
        current_phase="macro"
    )
    
    try:
        print(f"\nTesting macro_agent with {athlete.skillLevel.value} athlete...")
        result = macro_agent(state)
        
        if result.get("error"):
            print(f"Error: {result['error']}")
            return False
        
        macro = result["macro_plan"]
        print(f"Macro plan generated successfully!")
        print(f"   - {len(macro.mesocycle_stubs)} mesocycles planned")
        for meso in macro.mesocycle_stubs:
            print(f"      • {meso.phase.value}: {meso.num_weeks} weeks of {meso.focus.value}")
        
        return True
        
    except Exception as e:
        print(f"Exception: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_meso_agent_only():
    """Test only the meso agent with a sample macro plan."""
    from lib.agents import meso_agent
    
    print("\n" + "="*80)
    print("TESTING MESO AGENT ONLY")
    print("="*80)
    
    athlete = create_test_athlete()
    
    # Create a sample macro plan
    sample_macro = MacroCycle(
        cycle_start_date="2025-09-01",
        target_meet=Meet(name="State Championships", date="2026-02-15"),
        mesocycle_stubs=[
            MesoCycleStub(
                phase=PhaseType.GPP,
                num_weeks=6,
                focus=FocusType.AEROBIC,
                start_date="2025-09-01"
            ),
            MesoCycleStub(
                phase=PhaseType.SPP,
                num_weeks=5,
                focus=FocusType.THRESHOLD,
                start_date="2025-10-13"
            )
        ]
    )
    
    state = AgentState(
        athlete_profile=athlete,
        macro_plan=sample_macro,
        meso_plan=[],
        micro_plan=[],
        daily_workouts=[],
        messages=[],
        next_agent="meso",
        current_phase="meso"
    )
    
    try:
        print(f"\nTesting meso_agent with {len(sample_macro.mesocycle_stubs)} mesocycles...")
        result = meso_agent(state)
        
        if result.get("error"):
            print(f"Error: {result['error']}")
            return False
        
        meso_plans = result["meso_plan"]
        print(f"Meso plans generated successfully!")
        print(f"   - {len(meso_plans)} detailed mesocycles created")
        for i, meso in enumerate(meso_plans, 1):
            print(f"      • Mesocycle {i}: {len(meso.micro_cycle_stubs)} weeks")
        
        return True
        
    except Exception as e:
        print(f"Exception: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return False


# ══════════════════════════════════════════════════════════════════════════════
# RUN TESTS
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("\nSWIM PROGRAM DIRECTOR - WORKFLOW TESTS")
    print(f"   Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    results = {}
    
    # Run individual agent tests first (faster)
    results["macro_agent"] = test_macro_agent_only()
    results["meso_agent"] = test_meso_agent_only()
    
    # Run full workflow test (slowest - calls LLMs)
    results["full_workflow"] = test_full_workflow()
    
    # Summary
    print("\n" + "="*80)
    print("TEST SUMMARY")
    print("="*80)
    total = len(results)
    passed = sum(1 for v in results.values() if v)
    
    for test_name, passed_flag in results.items():
        status = "PASSED" if passed_flag else "FAILED"
        print(f"{status}: {test_name}")
    
    print(f"\nTotal: {passed}/{total} tests passed")
    print(f"Completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Exit with appropriate code
    sys.exit(0 if passed == total else 1)
